import type { NextPage } from "next";
import Head from "next/head";
import DocsList from "../components/docs-list";
import Header from "../components/header";
import NewDocs from "../components/new-docs";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <NewDocs />
      <DocsList />
    </div>
  );
};

export default Home;
