import type { NextPage } from "next";
import { getSession } from "next-auth/client";
import Head from "next/head";
import DocsList from "../components/docs-list";
import Header from "../components/header";
import Login from "../components/login";
import NewDocs from "../components/new-docs";

export async function getServerSideProps(context: any) {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}

const Home: NextPage = ({ session }: any) => {
  if (!session) return <Login />;

  return (
    <div>
      <Head>
        <title>Next Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <NewDocs />
      <DocsList />
    </div>
  );
};

export default Home;
